# Dev overrides
replicaCount: 1

image:
  tag: latest
  pullPolicy: Always

ingress:
  host: animark-dev.827482.xyz

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

env:
  - name: ANIMARK_ENV
    value: development
  - name: LOG_LEVEL
    value: debug
