apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: cluster
  source:
    repoURL: https://grafana.github.io/helm-charts/
    chart: grafana
    targetRevision: 10.5.15
    helm:
      values: |
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - grafana.827482.xyz

        adminPassword: admin

        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: VictoriaMetrics
                type: prometheus
                url: http://vms-victoria-metrics-single-server.monitoring:8428
                access: proxy
                isDefault: true

        grafana.ini:
          server:
            root_url: https://grafana.827482.xyz
          auth:
            disable_login_form: false
          auth.anonymous:
            enabled: true

        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi

        service:
          type: ClusterIP
          port: 80
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
