apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: cluster
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-metrics-single
    targetRevision: 0.41.0
    helm:
      values: |
        nameOverride: vms

        server:
          persistentVolume:
            enabled: false
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
