apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-logs-collector
  namespace: argocd
spec:
  project: cluster
  source:
    repoURL: https://victoriametrics.github.io/helm-charts
    chart: victoria-logs-collector
    targetRevision: 0.3.6
    helm:
      values: |
        remoteWrite:
          - url: http://vls-victoria-logs-single-server.monitoring:9428

        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
